on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  terraform:
    name: Terraform plan and Apply
    permissions:
      contents: read
      id-token: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github/github_actions
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2
      - name: Terraform init and plan
        run: |
          terraform init
          terraform plan --var-file=terraform.tfvars -out terraform.plan
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: xoanmm
      - name: Apply terraform changes
        run: |
          terraform apply "terraform.plan"
